//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator
namespace Frank.Finance.Documents.Ubl.CommonSignatureComponentsCommonSignatureComponents
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    /// <summary>
    /// <para><ccts:Component xmlns:ccts="urn:un:unece:uncefact:documentation:2"><ccts:ComponentType>ABIE</ccts:ComponentType><ccts:DictionaryEntryName>UBL Document Signatures. Details</ccts:DictionaryEntryName><ccts:Definition>This class collects all signature information for a document.</ccts:Definition><ccts:ObjectClass>UBL Document Signatures</ccts:ObjectClass></ccts:Component></para>
    /// </summary>
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [XmlTypeAttribute("UBLDocumentSignaturesType", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonSignatureComponents-2")]
    [XmlRootAttribute("UBLDocumentSignatures", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonSignatureComponents-2")]
    public partial class UblDocumentSignaturesType
    {
        
        [XmlIgnoreAttribute()]
        private List<Frank.Finance.Documents.Ubl.SignatureAggregateComponentsSignatureAggregateComponents.SignatureInformationType> _signatureInformation;
        
        /// <summary>
        /// <para><ccts:Component xmlns:ccts="urn:un:unece:uncefact:documentation:2"><ccts:ComponentType>ASBIE</ccts:ComponentType><ccts:DictionaryEntryName>UBL Document Signatures. Signature Information
        ///                            </ccts:DictionaryEntryName><ccts:Definition>Each of these is scaffolding for a single digital signature.
        ///                            </ccts:Definition><ccts:Cardinality>1..n</ccts:Cardinality><ccts:ObjectClass>UBL Document Signatures</ccts:ObjectClass><ccts:PropertyTerm>Signature Information</ccts:PropertyTerm><ccts:AssociatedObjectClass>Signature Information</ccts:AssociatedObjectClass><ccts:RepresentationTerm>Signature Information</ccts:RepresentationTerm></ccts:Component></para>
        /// </summary>
        [XmlElementAttribute("SignatureInformation", Namespace="urn:oasis:names:specification:ubl:schema:xsd:SignatureAggregateComponents-2")]
        public List<Frank.Finance.Documents.Ubl.SignatureAggregateComponentsSignatureAggregateComponents.SignatureInformationType> SignatureInformation
        {
            get
            {
                return _signatureInformation;
            }
            set
            {
                _signatureInformation = value;
            }
        }
    }
}
