//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator
namespace Frank.Finance.Documents.Ubl.CoreComponentTypes
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [XmlTypeAttribute("CommitmentTypeQualifiersListType", Namespace="http://uri.etsi.org/01903/v1.3.2#")]
    public partial class CommitmentTypeQualifiersListType
    {
        
        [XmlIgnoreAttribute()]
        private List<AnyType> _commitmentTypeQualifier;
        
        [XmlElementAttribute("CommitmentTypeQualifier")]
        public List<AnyType> CommitmentTypeQualifier
        {
            get
            {
                return _commitmentTypeQualifier;
            }
            set
            {
                _commitmentTypeQualifier = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die CommitmentTypeQualifier-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the CommitmentTypeQualifier collection is empty.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool CommitmentTypeQualifierSpecified
        {
            get
            {
                return ((this.CommitmentTypeQualifier != null) 
                            && (this.CommitmentTypeQualifier.Count != 0));
            }
        }
    }
}
