//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator
namespace Frank.Finance.Documents.Ubl.CoreComponentTypes
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [XmlTypeAttribute("DSAKeyValueType", Namespace="http://www.w3.org/2000/09/xmldsig#")]
    [XmlRootAttribute("DSAKeyValue", Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class DsaKeyValueType
    {
        
        [XmlElementAttribute("P", DataType="base64Binary")]
        public Byte[] P { get; set; }
        
        [XmlElementAttribute("Q", DataType="base64Binary")]
        public Byte[] Q { get; set; }
        
        [XmlElementAttribute("G", DataType="base64Binary")]
        public Byte[] G { get; set; }
        
        [XmlElementAttribute("Y", DataType="base64Binary")]
        public Byte[] Y { get; set; }
        
        [XmlElementAttribute("J", DataType="base64Binary")]
        public Byte[] J { get; set; }
        
        [XmlElementAttribute("Seed", DataType="base64Binary")]
        public Byte[] Seed { get; set; }
        
        [XmlElementAttribute("PgenCounter", DataType="base64Binary")]
        public Byte[] PgenCounter { get; set; }
    }
}
