//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator
namespace Frank.Finance.Documents.Ubl.CoreComponentTypes
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [XmlTypeAttribute("QualifyingPropertiesType", Namespace="http://uri.etsi.org/01903/v1.3.2#")]
    [XmlRootAttribute("QualifyingProperties", Namespace="http://uri.etsi.org/01903/v1.3.2#")]
    public partial class QualifyingPropertiesType
    {
        
        [XmlElementAttribute("SignedProperties")]
        public SignedPropertiesType SignedProperties { get; set; }
        
        [XmlElementAttribute("UnsignedProperties")]
        public UnsignedPropertiesType UnsignedProperties { get; set; }
        
        [XmlAttributeAttribute("Target")]
        public string Target { get; set; }
        
        [XmlAttributeAttribute("Id")]
        public string Id { get; set; }
    }
}
