//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator
namespace Frank.Finance.Documents.Ubl.CoreComponentTypes
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [XmlTypeAttribute("ReferenceInfoType", Namespace="http://uri.etsi.org/01903/v1.3.2#")]
    [XmlRootAttribute("ReferenceInfo", Namespace="http://uri.etsi.org/01903/v1.3.2#")]
    public partial class ReferenceInfoType
    {
        
        [XmlElementAttribute("DigestMethod", Namespace="http://www.w3.org/2000/09/xmldsig#")]
        public Frank.Finance.Documents.Ubl.CoreComponentTypes.DigestMethodType DigestMethod { get; set; }
        
        [XmlElementAttribute("DigestValue", Namespace="http://www.w3.org/2000/09/xmldsig#", DataType="base64Binary")]
        public Byte[] DigestValue { get; set; }
        
        [XmlAttributeAttribute("Id")]
        public string Id { get; set; }
        
        [XmlAttributeAttribute("URI")]
        public string Uri { get; set; }
    }
}
