//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator
namespace Frank.Finance.Documents.Ubl.CoreComponentTypes
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [XmlTypeAttribute("ValidationDataType", Namespace="http://uri.etsi.org/01903/v1.4.1#")]
    [XmlRootAttribute("TimeStampValidationData", Namespace="http://uri.etsi.org/01903/v1.4.1#")]
    public partial class ValidationDataType
    {
        
        [XmlElementAttribute("CertificateValues", Namespace="http://uri.etsi.org/01903/v1.3.2#")]
        public Frank.Finance.Documents.Ubl.CoreComponentTypes.CertificateValuesType CertificateValues { get; set; }
        
        [XmlElementAttribute("RevocationValues", Namespace="http://uri.etsi.org/01903/v1.3.2#")]
        public Frank.Finance.Documents.Ubl.CoreComponentTypes.RevocationValuesType RevocationValues { get; set; }
        
        [XmlAttributeAttribute("Id")]
        public string Id { get; set; }
        
        [XmlAttributeAttribute("UR")]
        public string Ur { get; set; }
    }
}
